### ISSUE TITLE
'annotations' folder does not exist

### ISSUE THREAD

**Issue by meetviolet** [biswassanket/DocSegTr#1]
Hi,

When I try to run with command:
```bash
python tools/train_net_custom.py \
    --config-file configs/SOTR/R_101_DCN_doc.yaml \
    --eval-only \
    --num-gpus 1 \
    MODEL.WEIGHTS work_dir/.../model_final.pth
```

It shows that:

```
File "/home/root/anaconda3/envs/instaseg/lib/python3.7/site-packages/pycocotools/coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/publaynet/annotations/instances_val2017.json'
```

Then I found that the 'annotations' folder does not exist in publaynet.

Does anybody know about it?

**Comment by biswassanket** [comment]
Okay try to structure your data folder.... like /data/ ---> annotations and images (create them)
                                                                     /annotations/--->folder put the train and val annotations of publaynet with the names instances_train2017.json and instances_val2017.json (this is the coco format required for the code to run)
                                                                    /images/---> folder put the train and val publaynet images in the 'train' and 'val' folder respectively

**Comment by meetviolet** [comment]
So much thanks.   o(*^_^*)o

**Comment by yexujian** [comment]
> Okay try to structure your data folder.... like /data/ ---> annotations and images (create them)
> /annotations/--->folder put the train and val annotations of publaynet with the names instances_train2017.json and instances_val2017.json (this is the coco format required for the code to run)
> /images/---> folder put the train and val publaynet images in the 'train' and 'val' folder respectively

Hello, the link to the best model provided by the author is invalid. Do you still have it here? If it is still saved, can you send me a file or link?
