### ISSUE TITLE
How can I Fine tune the model.

### ISSUE THREAD

**Issue by AbdulDD** [biswassanket/DocSegTr#11]
Hey! there, I am planning to fine-tune this model. I found the command in repo that says to train from scratch, so can anyone tell me how to fine tune it using pre-trained weights?

**Comment by yexujian** [comment]
Hello, the link to the best model provided in github has expired. I would like to ask if you have downloaded a copy here. If so, can you provide me with a copy? Thank you.

**Comment by AbdulDD** [comment]
Sorry! I have misplaced those since I stopped working on it and moved to other tasks.
